#pragma once

// Dependency-free preprocessing prototype. Production integration belongs in the
// public configuration boundary after declaration placement is qualified.

#ifndef SIMDLIB_DETAIL_FLAGS_VECTORCALL
#define SIMDLIB_DETAIL_FLAGS_VECTORCALL
#endif
#ifndef SIMDLIB_DETAIL_FLAGS_REGISTER_ONLY
#define SIMDLIB_DETAIL_FLAGS_REGISTER_ONLY
#endif
#ifndef SIMDLIB_DETAIL_FLAGS_FORCE_INLINE
#define SIMDLIB_DETAIL_FLAGS_FORCE_INLINE
#endif
#ifndef SIMDLIB_DETAIL_FLAGS_FLATTEN
#define SIMDLIB_DETAIL_FLAGS_FLATTEN
#endif

#define SIMDLIB_DETAIL_FLAGS_CAT_RAW(left, right) left##right
#define SIMDLIB_DETAIL_FLAGS_CAT(left, right) SIMDLIB_DETAIL_FLAGS_CAT_RAW(left, right)

#define SIMDLIB_DETAIL_FLAGS_BOUNDARY_ static_assert(false, "SIMDLIB_FLAGS_ERROR_EMPTY");
#define SIMDLIB_DETAIL_FLAGS_BOUNDARY_Neither
#define SIMDLIB_DETAIL_FLAGS_BOUNDARY_In SIMDLIB_DETAIL_FLAGS_VECTORCALL
#define SIMDLIB_DETAIL_FLAGS_BOUNDARY_Out SIMDLIB_DETAIL_FLAGS_VECTORCALL
#define SIMDLIB_DETAIL_FLAGS_BOUNDARY_InOut SIMDLIB_DETAIL_FLAGS_VECTORCALL

#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_1_RegisterOnly SIMDLIB_DETAIL_FLAGS_REGISTER_ONLY
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_1_ForceInline SIMDLIB_DETAIL_FLAGS_FORCE_INLINE
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_1_Flatten SIMDLIB_DETAIL_FLAGS_FLATTEN
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_2_RegisterOnly_ForceInline SIMDLIB_DETAIL_FLAGS_REGISTER_ONLY SIMDLIB_DETAIL_FLAGS_FORCE_INLINE
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_2_RegisterOnly_Flatten SIMDLIB_DETAIL_FLAGS_REGISTER_ONLY SIMDLIB_DETAIL_FLAGS_FLATTEN
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_2_ForceInline_Flatten SIMDLIB_DETAIL_FLAGS_FORCE_INLINE SIMDLIB_DETAIL_FLAGS_FLATTEN
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_3_RegisterOnly_ForceInline_Flatten                                                                                      \
	SIMDLIB_DETAIL_FLAGS_REGISTER_ONLY SIMDLIB_DETAIL_FLAGS_FORCE_INLINE SIMDLIB_DETAIL_FLAGS_FLATTEN

#define SIMDLIB_DETAIL_FLAGS_BOUNDARY_RAW(mode) SIMDLIB_DETAIL_FLAGS_BOUNDARY_##mode
#define SIMDLIB_DETAIL_FLAGS_BOUNDARY(mode) SIMDLIB_DETAIL_FLAGS_BOUNDARY_RAW(mode)
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_1_RAW(a) SIMDLIB_DETAIL_FLAGS_MODIFIERS_1_##a
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_1(a) SIMDLIB_DETAIL_FLAGS_MODIFIERS_1_RAW(a)
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_2_RAW(a, b) SIMDLIB_DETAIL_FLAGS_MODIFIERS_2_##a##_##b
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_2(a, b) SIMDLIB_DETAIL_FLAGS_MODIFIERS_2_RAW(a, b)
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_3_RAW(a, b, c) SIMDLIB_DETAIL_FLAGS_MODIFIERS_3_##a##_##b##_##c
#define SIMDLIB_DETAIL_FLAGS_MODIFIERS_3(a, b, c) SIMDLIB_DETAIL_FLAGS_MODIFIERS_3_RAW(a, b, c)

#define SIMDLIB_DETAIL_FLAGS_1(boundary) SIMDLIB_DETAIL_FLAGS_BOUNDARY(boundary)
#define SIMDLIB_DETAIL_FLAGS_2(boundary, a) SIMDLIB_DETAIL_FLAGS_BOUNDARY(boundary) SIMDLIB_DETAIL_FLAGS_MODIFIERS_1(a)
#define SIMDLIB_DETAIL_FLAGS_3(boundary, a, b) SIMDLIB_DETAIL_FLAGS_BOUNDARY(boundary) SIMDLIB_DETAIL_FLAGS_MODIFIERS_2(a, b)
#define SIMDLIB_DETAIL_FLAGS_4(boundary, a, b, c) SIMDLIB_DETAIL_FLAGS_BOUNDARY(boundary) SIMDLIB_DETAIL_FLAGS_MODIFIERS_3(a, b, c)
#define SIMDLIB_DETAIL_FLAGS_5(...) static_assert(false, "SIMDLIB_FLAGS_ERROR_TOO_MANY");

// Arity one deliberately includes an empty invocation. The empty boundary
// mapping diagnoses that case without __VA_OPT__ or a compiler extension.
#define SIMDLIB_DETAIL_FLAGS_ARITY_IMPL(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, count, ...) count
#define SIMDLIB_DETAIL_FLAGS_ARITY_EXPAND(arguments) SIMDLIB_DETAIL_FLAGS_ARITY_IMPL arguments
#define SIMDLIB_DETAIL_FLAGS_ARITY(...) SIMDLIB_DETAIL_FLAGS_ARITY_EXPAND((__VA_ARGS__, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 3, 2, 1))

#define SIMDLIB_DETAIL_FLAGS_DISPATCH(count) SIMDLIB_DETAIL_FLAGS_CAT(SIMDLIB_DETAIL_FLAGS_, count)
#define SIMDLIB_DETAIL_FLAGS_EXPAND(...) __VA_ARGS__

#define SIMD_FLAGS(...) SIMDLIB_DETAIL_FLAGS_EXPAND(SIMDLIB_DETAIL_FLAGS_DISPATCH(SIMDLIB_DETAIL_FLAGS_ARITY(__VA_ARGS__))(__VA_ARGS__))
