cmake_minimum_required(VERSION 3.31)
if(DEFINED OBSERVED_CASES)
    set(actual "${OBSERVED_CASES}")
else()
    execute_process(COMMAND "${RUNNER}" --list-tests --verbosity quiet
        OUTPUT_VARIABLE actual ERROR_VARIABLE error RESULT_VARIABLE status TIMEOUT 30)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Catch2 discovery failed: ${error}")
    endif()
endif()
string(REPLACE "\r\n" "\n" actual "${actual}")
string(STRIP "${actual}" actual)
string(REPLACE "\n" ";" actual "${actual}")
include("${CMAKE_CURRENT_LIST_DIR}/ExpectedCases.cmake")
set(expected ${SIMDLIB_EXPECTED_CODEGEN_CASES})
list(SORT actual)
list(SORT expected)
if(NOT "${actual}" STREQUAL "${expected}")
    message(FATAL_ERROR "Expected case coverage mismatch: expected ${expected}, discovered ${actual}")
endif()
