cmake_minimum_required(VERSION 3.31)

# Apply independent FileCheck files to one already selected LLVM body. Rule files
# use BEGIN/END sentinels for whole-body negatives; the LLVM text stays intact.
foreach(required IN ITEMS BODY_FILE FILECHECK RULES OUTPUT_DIRECTORY)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "CheckInstructions requires ${required}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(REMOVE "${OUTPUT_DIRECTORY}/passed.txt")
include("${CMAKE_CURRENT_LIST_DIR}/ToolIdentity.cmake")
simdlib_codegen_tool_identity("${FILECHECK}" FileCheck checker)
if(NOT EXISTS "${BODY_FILE}")
    message(FATAL_ERROR "Missing extracted body: ${BODY_FILE}")
endif()
file(READ "${BODY_FILE}" body)
if(INPUT_KIND STREQUAL "CONSTANTS")
    if(NOT body MATCHES "0x[0-9A-Fa-f]+ [0-9A-Fa-f]+")
        message(FATAL_ERROR "Empty or invalid LLVM constant dump: ${BODY_FILE}")
    endif()
elseif(NOT body MATCHES "[0-9A-Fa-f]+:[ \t]+[0-9A-Fa-f][0-9A-Fa-f][ \t]+")
    message(FATAL_ERROR "Empty or invalid extracted instruction body: ${BODY_FILE}")
endif()
set(input "${OUTPUT_DIRECTORY}/input.txt")
file(WRITE "${input}" "CODEGEN-BEGIN\n${body}\nCODEGEN-END\n")
if(NOT INPUT_KIND STREQUAL "CONSTANTS" AND DEFINED ALLOW_MNEMONICS AND NOT ALLOW_MNEMONICS STREQUAL "")
    include("${CMAKE_CURRENT_LIST_DIR}/InstructionAllowlist.cmake")
    simdlib_check_instruction_allowlist("${body}" "${ALLOW_MNEMONICS}")
endif()
set(index 0)
set(failures "")
foreach(rule IN LISTS RULES)
    if(NOT IS_ABSOLUTE "${rule}" OR NOT EXISTS "${rule}")
        message(FATAL_ERROR "Missing absolute rule file: ${rule}")
    endif()
    math(EXPR index "${index} + 1")
    execute_process(COMMAND "${FILECHECK}" "${rule}" "--input-file=${input}"
        --dump-input=fail ${FILECHECK_ARGS}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${OUTPUT_DIRECTORY}/filecheck-${index}.txt"
        "rule=${rule}\nchecker=${checker_PATH}\nversion=${checker_VERSION}\nexit=${result}\n${output}${error}")
    if(NOT result EQUAL 0)
        string(APPEND failures "\n${rule}: ${error}")
    endif()
endforeach()
if(NOT failures STREQUAL "")
    message(FATAL_ERROR "Instruction expectations failed in ${OUTPUT_DIRECTORY}:${failures}")
endif()
file(WRITE "${OUTPUT_DIRECTORY}/passed.txt" "FileCheck ${checker_VERSION}: ${index} independent rules passed\n")
