include_guard(GLOBAL)

# region Metadata parsing

# @brief Collects top-level LLVM readobj blocks without consuming nested auxiliary records.
# @param text LLVM structured text, with Unix line endings.
# @param kind Section or Symbol block name.
# @param output Variable receiving the ordered block list.
function(simdlib_codegen_metadata_blocks text kind output)
    if(text MATCHES ";")
        message(FATAL_ERROR "Unsupported semicolon in object metadata identity")
    endif()
    set(blocks "")
    set(active OFF)
    # Scan offsets rather than a CMake line list: LLVM's opening '[' on one
    # line would otherwise prevent list separation until its closing ']'.
    set(remaining "${text}\n")
    while(NOT remaining STREQUAL "")
        string(FIND "${remaining}" "\n" newline)
        string(SUBSTRING "${remaining}" 0 ${newline} line)
        math(EXPR next "${newline} + 1")
        string(SUBSTRING "${remaining}" ${next} -1 remaining)
        if(line STREQUAL "  ${kind} {")
            if(active)
                message(FATAL_ERROR "Malformed nested ${kind} metadata")
            endif()
            set(active ON)
            set(block "${line}\n")
        elseif(active)
            string(APPEND block "${line}\n")
            if(line STREQUAL "  }")
                list(APPEND blocks "${block}")
                set(active OFF)
            endif()
        endif()
    endwhile()
    if(active OR NOT blocks)
        message(FATAL_ERROR "Missing or unterminated ${kind} metadata")
    endif()
    set(${output} "${blocks}" PARENT_SCOPE)
endfunction()

# @brief Reads one required direct field from a readobj metadata block.
# @param block Section or symbol block.
# @param field Direct member name.
# @param output Variable receiving its text value.
function(simdlib_codegen_metadata_field block field output)
    string(REGEX MATCHALL "\n    ${field}: [^\n]+" matches "${block}")
    list(LENGTH matches count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected one ${field} metadata field")
    endif()
    string(REGEX REPLACE "^\n    ${field}: " "" value "${matches}")
    if(field MATCHES "^(Value|Size|RawDataSize|Index|Number)$" AND
            NOT value MATCHES "^(0x[0-9A-Fa-f]+|[0-9]+)$")
        message(FATAL_ERROR "Malformed numeric ${field} metadata: ${value}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

# @brief Reads a symbol's exact name and numeric section, preserving COFF decoration.
# @param block Symbol block.
# @param format Qualified object format.
# @param name_output Variable receiving the exact symbol name.
# @param section_output Variable receiving the numeric section index.
function(simdlib_codegen_symbol_identity block format name_output section_output)
    simdlib_codegen_metadata_field("${block}" Name name)
    if(format STREQUAL "elf64-x86-64")
        string(REGEX REPLACE " \\([0-9]+\\)$" "" name "${name}")
    endif()
    simdlib_codegen_metadata_field("${block}" Section section)
    if(NOT section MATCHES " \\((0x[0-9A-Fa-f]+|-?[0-9]+)\\)$")
        message(FATAL_ERROR "Unsupported symbol section: ${section}")
    endif()
    math(EXPR index "${CMAKE_MATCH_1}")
    set(${name_output} "${name}" PARENT_SCOPE)
    set(${section_output} "${index}" PARENT_SCOPE)
endfunction()

# @brief Resolves an exact unique defined function and establishes its metadata boundary.
# @param metadata LLVM readobj file-header, section and symbol output.
# @param symbol Exact emitted function name, without demangling.
# @param prefix Prefix receiving FORMAT, SECTION, START, SIZE, SYMBOLS and LLVM SELECTION arguments.
function(simdlib_codegen_function_metadata metadata symbol prefix)
    string(REGEX MATCHALL "\nFormat: [^\n]+" formats "\n${metadata}")
    list(LENGTH formats format_count)
    if(NOT format_count EQUAL 1)
        message(FATAL_ERROR "Expected exactly one object, not an archive or empty metadata")
    endif()
    string(REGEX REPLACE "^\nFormat: " "" format "${formats}")
    if(NOT format MATCHES "^(COFF-x86-64|elf64-x86-64)$")
        message(FATAL_ERROR "Unsupported object format: ${format}")
    endif()
    if(format STREQUAL "elf64-x86-64" AND NOT metadata MATCHES "\n  Type: Relocatable ")
        message(FATAL_ERROR "Extraction requires a relocatable ELF object")
    endif()
    simdlib_codegen_metadata_blocks("${metadata}" Symbol symbols)
    simdlib_codegen_metadata_blocks("${metadata}" Section sections)
    set(found 0)
    foreach(block IN LISTS symbols)
        simdlib_codegen_symbol_identity("${block}" "${format}" name section)
        if(name STREQUAL symbol)
            math(EXPR found "${found} + 1")
            set(selected "${block}")
            set(selected_section "${section}")
        endif()
    endforeach()
    if(NOT found EQUAL 1)
        message(FATAL_ERROR "Expected one exact symbol '${symbol}', found ${found}")
    endif()
    if(NOT selected MATCHES "\n    (ComplexType|Type): Function ")
        message(FATAL_ERROR "Selected symbol is not a function: ${symbol}")
    endif()
    set(section_found 0)
    foreach(block IN LISTS sections)
        if(format STREQUAL "COFF-x86-64")
            simdlib_codegen_metadata_field("${block}" Number index)
        else()
            simdlib_codegen_metadata_field("${block}" Index index)
        endif()
        if(index EQUAL selected_section)
            math(EXPR section_found "${section_found} + 1")
            set(section_block "${block}")
        endif()
    endforeach()
    if(NOT section_found EQUAL 1 OR selected_section LESS_EQUAL 0)
        message(FATAL_ERROR "Missing or ambiguous defining section for ${symbol}")
    endif()
    simdlib_codegen_metadata_field("${selected}" Value start)
    math(EXPR start "${start}")
    if(format STREQUAL "COFF-x86-64")
        # COFF function symbols usually omit size. An exclusive executable COMDAT
        # section supplies a trustworthy end; shared sections are rejected.
        if(NOT section_block MATCHES "IMAGE_SCN_MEM_EXECUTE" OR
                NOT section_block MATCHES "IMAGE_SCN_LNK_COMDAT" OR NOT start EQUAL 0)
            message(FATAL_ERROR "COFF extraction requires an exclusive /Gy function section")
        endif()
        simdlib_codegen_metadata_field("${section_block}" RawDataSize size)
        foreach(block IN LISTS symbols)
            simdlib_codegen_symbol_identity("${block}" "${format}" name section)
            if(section EQUAL selected_section AND NOT name STREQUAL symbol AND
                    block MATCHES "\n    ComplexType: Function ")
                message(FATAL_ERROR "Ambiguous shared COFF function section: ${symbol}, ${name}")
            endif()
        endforeach()
    else()
        if(NOT section_block MATCHES "SHF_EXECINSTR")
            message(FATAL_ERROR "ELF function section is not executable")
        endif()
        simdlib_codegen_metadata_field("${selected}" Size size)
    endif()
    math(EXPR size "${size}")
    if(size LESS 1)
        message(FATAL_ERROR "Empty function metadata: ${symbol}")
    endif()
    if(format STREQUAL "COFF-x86-64")
        simdlib_codegen_metadata_field("${section_block}" RawDataSize section_size)
    else()
        simdlib_codegen_metadata_field("${section_block}" Size section_size)
    endif()
    math(EXPR end "${start} + ${size}")
    if(end GREATER section_size)
        message(FATAL_ERROR "Function extends past its defining section")
    endif()
    foreach(field IN ITEMS format start size)
        string(TOUPPER "${field}" upper)
        set(${prefix}_${upper} "${${field}}" PARENT_SCOPE)
    endforeach()
    set(${prefix}_SECTION "${selected_section}" PARENT_SCOPE)
    set(${prefix}_SECTIONS "${sections}" PARENT_SCOPE)
    set(${prefix}_SYMBOLS "${symbols}" PARENT_SCOPE)
    simdlib_codegen_metadata_field("${section_block}" Name section_name)
    # Both supported readers append the section-name table offset/bytes here.
    string(REGEX REPLACE " \\([^\n]*\\)$" "" section_name "${section_name}")
    if(NOT section_name MATCHES "^[A-Za-z0-9_.$?-]+$")
        message(FATAL_ERROR "Unsupported exact section name: ${section_name}")
    endif()
    set(section_matches 0)
    foreach(block IN LISTS sections)
        simdlib_codegen_metadata_field("${block}" Name candidate)
        string(REGEX REPLACE " \\([^\n]*\\)$" "" candidate "${candidate}")
        if(candidate STREQUAL section_name)
            math(EXPR section_matches "${section_matches} + 1")
        endif()
    endforeach()
    set(selection --disassemble "--section=${section_name}")
    if(section_matches GREATER 1)
        # COFF /Gy sections can share names. Select the entry and every interior
        # symbol so LLVM does not stop inspection at an internal branch label.
        set(names "${symbol}")
        foreach(block IN LISTS symbols)
            simdlib_codegen_symbol_identity("${block}" "${format}" name section)
            if(section EQUAL selected_section)
                simdlib_codegen_metadata_field("${block}" Value value)
                if(value GREATER start AND value LESS end)
                    list(APPEND names "${name}")
                endif()
            endif()
        endforeach()
        list(REMOVE_DUPLICATES names)
        foreach(name IN LISTS names)
            if(NOT name MATCHES "^[A-Za-z_?$@.][A-Za-z0-9_?$@.]*$")
                message(FATAL_ERROR "Unsupported selection symbol: ${name}")
            endif()
            set(matches 0)
            foreach(block IN LISTS symbols)
                simdlib_codegen_symbol_identity("${block}" "${format}" candidate section)
                if(candidate STREQUAL name)
                    math(EXPR matches "${matches} + 1")
                endif()
            endforeach()
            if(NOT matches EQUAL 1)
                message(FATAL_ERROR "Ambiguous selection symbol: ${name}")
            endif()
        endforeach()
        list(JOIN names "," names)
        set(selection "--disassemble-symbols=${names}" "--section=${section_name}")
    endif()
    list(APPEND selection "--start-address=${start}" "--stop-address=${end}" --disassemble-zeroes)
    set(${prefix}_SELECTION "${selection}" PARENT_SCOPE)
endfunction()

# endregion
