cmake_minimum_required(VERSION 3.31)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
set(body "0 <probe>:\n 0: c5 f1 72 f0 03  vpslld xmm2, xmm0, 0x3\n 5: c5 e9 fe d0  vpaddd xmm2, xmm2, xmm0\n 9: c3  ret\n")
set(rules "${CMAKE_CURRENT_LIST_DIR}/rules/operation.check;${root}/tests/codegen/contracts/no-call-stack.check")
set(expect_failure TRUE)
if(CASE STREQUAL "valid")
    set(expect_failure FALSE)
elseif(CASE STREQUAL "after-return")
    string(APPEND body " a: e8 00 00 00 00  call wrong_target\n")
elseif(CASE STREQUAL "extra-before")
    string(PREPEND body " 0: c5 f1 72 f0 03  vpslld xmm2, xmm0, 0x3\n")
elseif(CASE STREQUAL "extra-after")
    string(APPEND body " a: c5 f1 72 f0 03  vpslld xmm2, xmm0, 0x3\n")
elseif(CASE STREQUAL "width")
    string(REPLACE xmm ymm body "${body}")
elseif(CASE STREQUAL "immediate")
    string(REPLACE 0x3 0x4 body "${body}")
elseif(CASE STREQUAL "operand")
    string(REPLACE "vpaddd xmm2, xmm2" "vpaddd xmm2, xmm1" body "${body}")
elseif(CASE MATCHES "^target")
    set(body "0 <probe>:\n 0: e8 00 00 00 00  call 0x5\n 1: IMAGE_REL_AMD64_REL32 required_target\n 5: c3  ret\n")
    set(rules "${CMAKE_CURRENT_LIST_DIR}/rules/target.check")
    if(CASE STREQUAL "target-valid")
        set(expect_failure FALSE)
    else()
        string(REPLACE required_target incorrect_target body "${body}")
    endif()
elseif(CASE MATCHES "^cookie")
    set(body "0 <probe>:\n 0: 48 83 ec 28  sub rsp, 0x28\n 4: 48 8b 05 00 00 00 00  mov rax, qword ptr [rip]\n 7: IMAGE_REL_AMD64_REL32 __security_cookie\n b: 48 33 c4  xor rax, rsp\n e: 48 89 44 24 10  mov qword ptr [rsp + 0x10], rax\n 13: 48 8b 4c 24 10  mov rcx, qword ptr [rsp + 0x10]\n 18: 48 33 cc  xor rcx, rsp\n 1b: e8 00 00 00 00  call 0x20\n 1c: IMAGE_REL_AMD64_REL32 __security_check_cookie\n 20: 48 83 c4 28  add rsp, 0x28\n 24: c3  ret\n")
    set(rules "${CMAKE_CURRENT_LIST_DIR}/rules/cookie.check")
    if(CASE STREQUAL "cookie-valid")
        set(expect_failure FALSE)
    elseif(CASE STREQUAL "cookie-target")
        string(REPLACE __security_check_cookie unrelated_call body "${body}")
    elseif(CASE STREQUAL "cookie-extra")
        string(APPEND body " 25: e8 00 00 00 00  call unrelated_call\n")
    else()
        list(APPEND rules "${root}/tests/codegen/contracts/no-call-stack.check")
    endif()
elseif(CASE STREQUAL "return-only")
    set(body "0 <identity>:\n 0: c3  ret\n")
    set(rules "${root}/tests/codegen/contracts/return.check;${root}/tests/codegen/contracts/no-call-stack.check")
    set(expect_failure FALSE)
elseif(CASE STREQUAL "empty")
    set(body "0 <empty>:\n")
elseif(CASE STREQUAL "allowlist")
    set(ALLOW_MNEMONICS "vpslld|ret")
elseif(CASE MATCHES "^add-")
    set(body "0 <probe>:\n 0: c5 f0 58 c0  vaddps xmm0, xmm1, xmm0\n 4: c3  ret\n")
    set(rules "${root}/tests/codegen/register/add.check")
    if(CASE STREQUAL "add-valid")
        set(expect_failure FALSE)
    else()
        string(REPLACE "xmm1, xmm0" "xmm0, xmm0" body "${body}")
    endif()
elseif(CASE MATCHES "^transfer-")
    set(body "0 <probe>:\n 0: c5 f8 10 01  vmovups xmm0, xmmword ptr [rcx]\n 4: c5 f8 58 0a  vaddps xmm1, xmm0, xmmword ptr [rdx]\n 8: c4 c1 78 11 08  vmovups xmmword ptr [r8], xmm1\n d: c3  ret\n")
    set(rules "${root}/tests/codegen/register/transfer.check")
    if(CASE STREQUAL "transfer-valid")
        set(expect_failure FALSE)
    elseif(CASE STREQUAL "transfer-extra-before-add")
        string(REPLACE " 4:" " 3: c5 f8 58 c0  vaddps xmm0, xmm0, xmm0\n 4:" body "${body}")
    else()
        string(REPLACE " 8:" " 7: c5 f8 58 c0  vaddps xmm0, xmm0, xmm0\n 8:" body "${body}")
    endif()
elseif(CASE MATCHES "^blend-")
    set(body "0 <probe>:\n 0: c5 f0 57 c9  vxorps xmm1, xmm1, xmm1\n 4: c4 e3 79 0c c1 08  vblendps xmm0, xmm0, xmm1, 0x8\n a: c3  ret\n")
    set(rules "${root}/tests/codegen/partial-register/import-blend.check")
    if(CASE STREQUAL "blend-valid")
        set(expect_failure FALSE)
    else()
        string(REPLACE 0x8 0x4 body "${body}")
    endif()
elseif(CASE MATCHES "^zero-")
    set(body "0 <probe>:\n 0: c5 f8 57 c0  vxorps xmm0, xmm0, xmm0\n 4: c3  ret\n")
    set(rules "${root}/tests/codegen/register/zero.check")
    if(CASE STREQUAL "zero-valid")
        set(expect_failure FALSE)
    else()
        string(REPLACE "xmm0, xmm0, xmm0" "xmm0, xmm0, xmm1" body "${body}")
    endif()
elseif(CASE MATCHES "^abi-")
    set(body "0 <simdlib_contract_abi_binary_caller>:\n 0: 48 83 ec 08  sub rsp, 0x8\n 4: e8 00 00 00 00  call 0x9\n 5: R_X86_64_PLT32 simdlib_contract_abi_binary_callee-0x4\n 9: 48 83 c4 08  add rsp, 0x8\n d: c3  ret\n")
    set(rules "${root}/tests/codegen/register/abi-call.check")
    if(CASE STREQUAL "abi-valid")
        set(expect_failure FALSE)
    elseif(CASE STREQUAL "abi-target-suffix")
        string(REPLACE "callee-0x4" "callee_wrong-0x4" body "${body}")
    elseif(CASE STREQUAL "abi-target-prefix")
        set(rules "${root}/tests/codegen/register/abi-caller.check")
        string(REPLACE "simdlib_contract_abi_binary_callee-0x4" "wrong_simdlib_contract_abi_binary_callee-0x4" body "${body}")
    elseif(CASE STREQUAL "abi-extra-frame-before")
        string(REPLACE " 0:" " 0: 48 89 04 24  mov qword ptr [rsp], rax\n 0:" body "${body}")
    else()
        string(APPEND body " e: 48 89 04 24  mov qword ptr [rsp], rax\n")
    endif()
else()
    message(FATAL_ERROR "Unknown harness case ${CASE}")
endif()
file(WRITE "${OUTPUT_DIRECTORY}/body.txt" "${body}")
execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DBODY_FILE=${OUTPUT_DIRECTORY}/body.txt" "-DFILECHECK=${FILECHECK}"
    "-DRULES=${rules}" "-DALLOW_MNEMONICS=${ALLOW_MNEMONICS}"
    "-DFILECHECK_ARGS=-DREG=xmm;-DMEM=xmmword;-DMASK=0x8;-DTARGET=simdlib_contract_abi_binary_callee"
    "-DOUTPUT_DIRECTORY=${OUTPUT_DIRECTORY}/check"
    -P "${root}/cmake/codegen/CheckInstructions.cmake"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${OUTPUT_DIRECTORY}/harness.txt" "exit=${result}\n${output}${error}")
if(expect_failure)
    if(result EQUAL 0 OR NOT "${error}" MATCHES "Instruction expectations failed|Forbidden instruction family|Empty or invalid")
        message(FATAL_ERROR "Expected specific rule rejection for ${CASE}: ${output}${error}")
    endif()
    if(EXISTS "${OUTPUT_DIRECTORY}/check/passed.txt")
        message(FATAL_ERROR "Failed check retained success")
    endif()
elseif(NOT result EQUAL 0)
    message(FATAL_ERROR "Valid ${CASE} rejected: ${output}${error}")
endif()
