include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/CodegenTests.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/CodegenCatch2.cmake")
simdlib_select_codegen_tools()
simdlib_codegen_catch2_dependency()
if(NOT SIMDLIB_SOURCE_ROOT)
    set(SIMDLIB_SOURCE_ROOT "${CMAKE_SOURCE_DIR}")
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set(driver msvc)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    set(driver clang-cl)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(driver clang)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 14)
    set(driver gcc)
else()
    message(FATAL_ERROR "Unsupported Register pilot compiler")
endif()
set(fixtures "${SIMDLIB_SOURCE_ROOT}/tests/codegen")
file(GLOB_RECURSE inputs CONFIGURE_DEPENDS
    "${SIMDLIB_SOURCE_ROOT}/include/*" "${SIMDLIB_SOURCE_ROOT}/cmake/codegen/*"
    "${SIMDLIB_SOURCE_ROOT}/cmake/development/Codegen*.cmake"
    "${fixtures}/register/*" "${fixtures}/partial-register/*" "${fixtures}/contracts/*"
    "${fixtures}/pilot/*" "${fixtures}/support/*")
add_custom_target(CodegenPilot)
if(COMMAND simdlib_register_development_target)
    simdlib_register_development_target(CodegenPilot OPTIMIZED_CODEGEN)
endif()
foreach(width IN ITEMS 128 256)
    if(width EQUAL 128)
        set(active 3)
        set(msvc_constant "?active_lane_filter@?$PartialRegister@I$0IA@$02@SimdLib@@0V?$array@I$03@std@@B")
    else()
        set(active 5)
        set(msvc_constant "?active_lane_filter@?$PartialRegister@I$0BAA@$04@SimdLib@@0V?$array@I$07@std@@B")
    endif()
    math(EXPR vector_bytes "${width}/8")
    math(EXPR binary_bytes "2 * ${vector_bytes}")
    set(decoration "")
    set(binary_decoration "")
    set(zero_decoration "")
    if(driver MATCHES "^(msvc|clang-cl)$")
        set(options /O1 /Ob2 /Gy /arch:AVX2 /GS)
        set(decoration "@@${vector_bytes}")
        set(binary_decoration "@@${binary_bytes}")
        set(zero_decoration "@@0")
    else()
        set(options -O1 -ffunction-sections -mavx2 -mno-fma -fstack-protector-strong)
    endif()
    set(configuration "${driver}-${CMAKE_CXX_COMPILER_VERSION}-x64-avx2-w${width}-provisional-checksoff-none-fmaoff-explicit-stackon")
    set(object_rows "")
    foreach(family IN ITEMS arithmetic transfer import abi)
        set(source "${fixtures}/register/${family}.cpp")
        set(geometry "f32-w${width}-nall-tonone-wnone-immnone-shapepilot")
        if(family STREQUAL "import")
            set(source "${fixtures}/partial-register/import.cpp")
            set(geometry "u32-w${width}-n${active}-tonone-wnone-immnone-shapeimport")
        endif()
        set(target "CodegenPilot_${family}_${width}")
        simdlib_add_codegen_fixture(TARGET ${target} SOURCE "${source}"
            CONFIGURATION "${configuration}" GEOMETRY "${geometry}"
            OPTIONS ${options} DEFINITIONS SIMDLIB_CONTRACT_WIDTH=${width}
                SIMDLIB_CONTRACT_ACTIVE=${active} SIMDLIB_HAS_FMA=0 NDEBUG INPUTS ${inputs})
        get_target_property(root ${target} SIMDLIB_CODEGEN_ROOT)
        string(APPEND object_rows "{R\"cfg($<TARGET_OBJECTS:${target}>)cfg\", R\"cfg(${root}/inputs.cmake)cfg\", R\"cfg(${root}/build.sha256)cfg\", R\"cfg(${root}/configuration.txt)cfg\"},\n")
    endforeach()
    set(constants "")
    if(driver STREQUAL "msvc")
        set(constants "${msvc_constant}")
    elseif(driver STREQUAL "gcc")
        set(constants .LC0)
    endif()
    # Only build identities live here. Assertions are readable Catch2 definitions.
    set(symbol_rows "")
    foreach(spec IN ITEMS "operation_add_f32|${binary_decoration}|0|"
            "operation_zero_f32|${zero_decoration}|0|" "expression_native|${decoration}|0|"
            "transfer_load_operate_store||1|" "value_import|${decoration}|2|${constants}"
            "abi_binary_caller|${binary_decoration}|3|" "abi_binary_callee|${binary_decoration}|3|")
        string(REPLACE "|" ";" fields "${spec}")
        list(GET fields 0 name)
        list(GET fields 1 suffix)
        list(GET fields 2 object)
        list(GET fields 3 constant)
        string(APPEND symbol_rows "{\"simdlib_contract_${name}\", \"simdlib_contract_${name}${suffix}\", ${object}, R\"cfg(${constant})cfg\"},\n")
    endforeach()
    set(runner_root "${CMAKE_CURRENT_BINARY_DIR}/codegen-contracts/runner-${width}")
    configure_file("${fixtures}/support/Configuration.h.in" "${runner_root}/Configuration.h.in" @ONLY)
    file(GENERATE OUTPUT "${runner_root}/Configuration.h" INPUT "${runner_root}/Configuration.h.in")
    set(runner CodegenTests${width})
    add_executable(${runner}
        "${fixtures}/support/Process.cpp" "${fixtures}/support/Inspection.cpp" "${fixtures}/support/Applicability.cpp"
        "${fixtures}/support/CodegenFixture.cpp" "${fixtures}/support/Function.cpp" "${fixtures}/support/FileCheck.cpp"
        "${fixtures}/pilot/ExpectedRules.cpp"
        "${fixtures}/register/Arithmetic.tests.cpp" "${fixtures}/register/Transfer.tests.cpp"
        "${fixtures}/register/Abi.tests.cpp" "${fixtures}/partial-register/Import.tests.cpp")
    target_compile_features(${runner} PRIVATE cxx_std_20)
    if(MSVC)
        target_compile_options(${runner} PRIVATE /utf-8)
    endif()
    set_property(TARGET ${runner} PROPERTY CXX_SCAN_FOR_MODULES OFF)
    target_include_directories(${runner} PRIVATE "${fixtures}/support" "${runner_root}")
    target_link_libraries(${runner} PRIVATE Catch2::Catch2WithMain)
    foreach(family IN ITEMS arithmetic transfer import abi)
        add_dependencies(${runner} CodegenPilot_${family}_${width}Receipt)
    endforeach()
    add_dependencies(CodegenPilot ${runner})
    simdlib_discover_codegen_tests(${runner} "Codegen.${configuration}.")
    # Independent case inventory: discovery is checked even when CTest is filtered.
    add_custom_command(TARGET ${runner} POST_BUILD
        COMMAND "${CMAKE_COMMAND}" "-DRUNNER=$<TARGET_FILE:${runner}>"
            -P "${fixtures}/pilot/VerifyDiscovery.cmake" VERBATIM)
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/CodegenHarness.cmake")
