include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/CodegenTests.cmake")
simdlib_select_codegen_tools()
if(NOT SIMDLIB_SOURCE_ROOT)
    set(SIMDLIB_SOURCE_ROOT "${CMAKE_SOURCE_DIR}")
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set(driver msvc)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    set(driver clang-cl)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(driver clang)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 14)
    set(driver gcc)
else()
    message(FATAL_ERROR "Unsupported Register pilot compiler")
endif()
set(fixtures "${SIMDLIB_SOURCE_ROOT}/tests/codegen")
file(GLOB_RECURSE inputs CONFIGURE_DEPENDS
    "${SIMDLIB_SOURCE_ROOT}/include/*" "${SIMDLIB_SOURCE_ROOT}/cmake/codegen/*"
    "${SIMDLIB_SOURCE_ROOT}/cmake/development/Codegen*.cmake"
    "${fixtures}/register/*" "${fixtures}/partial-register/*" "${fixtures}/contracts/*"
    "${fixtures}/pilot/*")
add_custom_target(CodegenPilot)
if(COMMAND simdlib_register_development_target)
    simdlib_register_development_target(CodegenPilot OPTIMIZED_CODEGEN)
endif()
set(expected "")
foreach(width IN ITEMS 128 256)
    if(width EQUAL 128)
        set(active 3)
    else()
        set(active 5)
    endif()
    math(EXPR vector_bytes "${width}/8")
    if(driver MATCHES "^(msvc|clang-cl)$")
        set(options /O1 /Ob2 /Gy /arch:AVX2 /GS)
        set(decoration "@@${vector_bytes}")
        math(EXPR binary_bytes "2 * ${vector_bytes}")
        set(binary_decoration "@@${binary_bytes}")
        set(zero_decoration "@@0")
    else()
        set(options -O1 -ffunction-sections -mavx2 -mno-fma -fstack-protector-strong)
        set(decoration "")
        set(binary_decoration "")
        set(zero_decoration "")
    endif()
    set(configuration "${driver}-${CMAKE_CXX_COMPILER_VERSION}-x64-avx2-w${width}-provisional-checksoff-none-fmaoff-explicit-stackon")
    set(geometry "f32-w${width}-nall-tonone-wnone-immnone-shapepilot")
    foreach(family IN ITEMS arithmetic transfer abi import)
        set(source "${fixtures}/register/${family}.cpp")
        if(family STREQUAL "import")
            set(source "${fixtures}/partial-register/import.cpp")
            set(fixture_geometry "u32-w${width}-n${active}-tonone-wnone-immnone-shapeimport")
        else()
            set(fixture_geometry "${geometry}")
        endif()
        set(target "CodegenPilot_${family}_${width}")
        simdlib_add_codegen_fixture(TARGET ${target} SOURCE "${source}"
            CONFIGURATION "${configuration}" GEOMETRY "${fixture_geometry}"
            OPTIONS ${options} DEFINITIONS SIMDLIB_CONTRACT_WIDTH=${width}
                SIMDLIB_CONTRACT_ACTIVE=${active} SIMDLIB_HAS_FMA=0 NDEBUG
            INPUTS ${inputs})
        add_dependencies(CodegenPilot ${target}Receipt)
    endforeach()
    # These case definitions are shared across drivers. Only the supplemental
    # selector controls its own additional fact, never a primary registration.
    foreach(case IN ITEMS operation.add_f32 operation.zero_f32 expression.native
            transfer.load_operate_store value.import abi.binary)
        set(family arithmetic)
        set(symbol "simdlib_contract_${case}")
        string(REPLACE "." "_" symbol "${symbol}")
        set(supplements "")
        set(allow "")
        set(rules "${fixtures}/contracts/no-call-stack.check;${fixtures}/contracts/return.check")
        set(member_rules "")
        set(constants "")
        if(case STREQUAL "operation.add_f32")
            string(APPEND symbol "${binary_decoration}")
            list(APPEND rules "${fixtures}/contracts/register-only.check" "${fixtures}/register/add.check")
            set(allow "vaddps|ret|nop")
        elseif(case STREQUAL "operation.zero_f32")
            string(APPEND symbol "${zero_decoration}")
            list(APPEND rules "${fixtures}/contracts/register-only.check" "${fixtures}/register/zero.check")
            set(allow "vxorps|vpxor|xorps|pxor|ret|nop")
        elseif(case STREQUAL "expression.native")
            string(APPEND symbol "${decoration}")
            list(APPEND rules "${fixtures}/contracts/register-only.check")
            set(allow "ret|nop")
        elseif(case STREQUAL "transfer.load_operate_store")
            set(family transfer)
            set(rules "${fixtures}/contracts/return.check")
            list(APPEND rules "${fixtures}/register/transfer.check")
        elseif(case STREQUAL "value.import")
            set(family import)
            string(APPEND symbol "${decoration}")
            set(rules "${fixtures}/contracts/return.check")
            list(APPEND rules "${fixtures}/partial-register/import.check")
        elseif(case STREQUAL "abi.binary")
            set(family abi)
            set(symbol "simdlib_contract_abi_binary_caller${binary_decoration};simdlib_contract_abi_binary_callee${binary_decoration}")
            set(rules "${fixtures}/contracts/function.check")
            set(member_rules "set(RULES_simdlib_contract_abi_binary_caller${binary_decoration} [==[${fixtures}/register/abi-caller.check]==])\nset(RULES_simdlib_contract_abi_binary_callee${binary_decoration} [==[${fixtures}/register/add.check;${fixtures}/contracts/return.check;${fixtures}/contracts/no-call-stack.check;${fixtures}/contracts/register-only.check]==])\n")
        endif()
        if(width EQUAL 128)
            set(reg xmm)
        else()
            set(reg ymm)
        endif()
        set(definition "${CMAKE_CURRENT_BINARY_DIR}/pilot-rules/${case}-${width}.cmake")
        file(WRITE "${definition}" "set(RULES [==[${rules}]==])\nset(ALLOW_MNEMONICS [==[${allow}]==])\nset(FILECHECK_ARGS -DREG=${reg} -DMEM=${reg}word -DTARGET=simdlib_contract_abi_binary_callee${binary_decoration})\n${member_rules}")
        set(selected_supplements "")
        if(case STREQUAL "operation.add_f32")
            set(supplement "${CMAKE_CURRENT_BINARY_DIR}/pilot-rules/add-supplement-${width}.cmake")
            file(WRITE "${supplement}" "set(RULES [==[${fixtures}/register/no-extra-move.check]==])\n")
            # The delimiter is reserved for fields; regex alternation uses a
            # character-class based shared selector for the two Clang drivers.
            set(selected_supplements "no-extra-move|clang(-cl)?|provisional|${supplement}")
        endif()
        if(family STREQUAL "transfer" OR family STREQUAL "import")
            foreach(fact IN ITEMS msvc-cookie no-call-stack)
                set(supplement "${CMAKE_CURRENT_BINARY_DIR}/pilot-rules/${fact}-${width}.cmake")
                file(WRITE "${supplement}" "set(RULES [==[${fixtures}/contracts/${fact}.check]==])\n")
                if(fact STREQUAL "msvc-cookie")
                    set(selector msvc)
                else()
                    # Matches exactly the supported GCC and Clang driver names.
                    set(selector "[cg].*")
                endif()
                list(APPEND selected_supplements "${fact}|${selector}|provisional|${supplement}")
            endforeach()
        endif()
        if(family STREQUAL "abi")
            set(supplement "${CMAKE_CURRENT_BINARY_DIR}/pilot-rules/abi-call-${width}.cmake")
            if(width EQUAL 256)
                set(call_rule abi-call256)
            else()
                set(call_rule abi-call)
            endif()
            file(WRITE "${supplement}" "set(RULES [==[${fixtures}/contracts/function.check]==])\nset(RULES_simdlib_contract_abi_binary_caller [==[${fixtures}/register/${call_rule}.check]==])\n")
            list(APPEND selected_supplements "aligned-call|gcc|provisional|${supplement}")
            set(supplement "${CMAKE_CURRENT_BINARY_DIR}/pilot-rules/abi-tail-${width}.cmake")
            file(WRITE "${supplement}" "set(RULES [==[${fixtures}/contracts/no-call-stack.check;${fixtures}/contracts/register-only.check]==])\nset(RULES_simdlib_contract_abi_binary_caller${binary_decoration} [==[${fixtures}/register/abi-tail.check]==])\nset(ALLOW_MNEMONICS_simdlib_contract_abi_binary_caller${binary_decoration} [==[jmp|nop]==])\n")
            list(APPEND selected_supplements "tail-call|[^g].*|provisional|${supplement}")
        endif()
        if(family STREQUAL "import")
            if(width EQUAL 128)
                set(mask 0x8)
                set(msvc_constant "?active_lane_filter@?$PartialRegister@I$0IA@$02@SimdLib@@0V?$array@I$03@std@@B")
            else()
                set(mask 0xe0)
                set(msvc_constant "?active_lane_filter@?$PartialRegister@I$0BAA@$04@SimdLib@@0V?$array@I$07@std@@B")
            endif()
            foreach(lowering IN ITEMS blend mask-msvc mask-gcc)
                set(supplement "${CMAKE_CURRENT_BINARY_DIR}/pilot-rules/import-${lowering}-${width}.cmake")
                set(content "set(RULES [==[${fixtures}/partial-register/import-${lowering}.check]==])\nset(FILECHECK_ARGS -DREG=${reg} -DMEM=${reg}word -DMASK=${mask})\n")
                if(lowering STREQUAL "blend")
                    set(selector "clang(-cl)?")
                else()
                    string(REPLACE "mask-" "" selector "${lowering}")
                    string(APPEND content "set(CONSTANT_RULES [==[${fixtures}/partial-register/mask${width}.check]==])\n")
                endif()
                file(WRITE "${supplement}" "${content}")
                list(APPEND selected_supplements "projection-${lowering}|${selector}|provisional|${supplement}")
            endforeach()
            if(driver STREQUAL "msvc")
                set(constants "${msvc_constant}")
            elseif(driver STREQUAL "gcc")
                set(constants .LC0)
            endif()
        endif()
        simdlib_add_codegen_case(ID "${case}" TARGET "CodegenPilot_${family}_${width}"
            PRIMARY "${definition}" DRIVER "${driver}" SYMBOLS ${symbol}
            SUPPLEMENTS ${selected_supplements} CONSTANT_SYMBOLS ${constants})
    endforeach()
    # Independent finite coverage ledger: do not derive this from emitted symbols
    # or from the registration helper's selected supplement list.
    foreach(case IN ITEMS operation.add_f32 operation.zero_f32 expression.native
            transfer.load_operate_store value.import abi.binary)
        if(case STREQUAL "value.import")
            set(case_geometry "u32-w${width}-n${active}-tonone-wnone-immnone-shapeimport")
        else()
            set(case_geometry "${geometry}")
        endif()
        list(APPEND expected "Codegen.${case}.${case_geometry}.${configuration}.primary")
    endforeach()
    if(driver STREQUAL "clang" OR driver STREQUAL "clang-cl")
        list(APPEND expected "Codegen.operation.add_f32.${geometry}.${configuration}.supplemental.no-extra-move")
    endif()
    if(driver STREQUAL "msvc")
        set(expected_fact msvc-cookie)
    else()
        set(expected_fact no-call-stack)
    endif()
    foreach(case IN ITEMS transfer.load_operate_store value.import)
        if(case STREQUAL "value.import")
            set(case_geometry "u32-w${width}-n${active}-tonone-wnone-immnone-shapeimport")
        else()
            set(case_geometry "${geometry}")
        endif()
        list(APPEND expected "Codegen.${case}.${case_geometry}.${configuration}.supplemental.${expected_fact}")
    endforeach()
    if(driver STREQUAL "gcc")
        set(abi_fact aligned-call)
    else()
        set(abi_fact tail-call)
    endif()
    list(APPEND expected "Codegen.abi.binary.${geometry}.${configuration}.supplemental.${abi_fact}")
    if(driver STREQUAL "msvc" OR driver STREQUAL "gcc")
        set(projection "mask-${driver}")
    else()
        set(projection blend)
    endif()
    list(APPEND expected "Codegen.value.import.u32-w${width}-n${active}-tonone-wnone-immnone-shapeimport.${configuration}.supplemental.projection-${projection}")
endforeach()
simdlib_finalize_codegen_cases(${expected})
