include_guard(GLOBAL)

if(NOT PROJECT_IS_TOP_LEVEL)
    message(FATAL_ERROR "Examples.cmake is available only to top-level SimdLib builds")
endif()
if(NOT TARGET SimdLib OR NOT TARGET SimdLibRegister)
    message(FATAL_ERROR "Examples.cmake requires the production SimdLib targets")
endif()

block(SCOPE_FOR VARIABLES)

if(SIMDLIB_BUILD_EXAMPLES)
    add_executable(ApiExamples examples/ApiExamples.cpp)
    simdlib_register_development_target(ApiExamples SMOKE_VALIDATION)
    target_link_libraries(ApiExamples PRIVATE SimdLib::SimdLib)
    simdlib_enable_development_warnings(ApiExamples)
	if(SIMDLIB_MSVC_STYLE_DRIVER)
        target_compile_options(ApiExamples PRIVATE /arch:AVX2)
    else()
        target_compile_options(ApiExamples PRIVATE -mavx2 -mfma -mbmi -mbmi2)
    endif()
    add_test(NAME ApiExamples COMMAND ApiExamples)
    set_tests_properties(ApiExamples PROPERTIES LABELS "EXAMPLES;AVX2;FMA;BMI")
    simdlib_set_coverage_profile_prefix(ApiExamples "ApiExamples")

	if(SIMDLIB_REGISTER_COMPILER_SUPPORTED)
		add_executable(RegisterExamples examples/RegisterExamples.cpp)
		simdlib_register_development_target(RegisterExamples SMOKE_VALIDATION)
		target_link_libraries(RegisterExamples PRIVATE SimdLib::Register)
		simdlib_enable_development_warnings(RegisterExamples)
		simdlib_enable_register_sse42(RegisterExamples)
		add_test(NAME RegisterExamples COMMAND RegisterExamples)
		set_tests_properties(RegisterExamples PROPERTIES LABELS "EXAMPLES;REGISTER;SSE42")
		simdlib_set_coverage_profile_prefix(RegisterExamples "RegisterExamples")
	endif()
endif()

endblock()
