cmake_policy(VERSION 3.20)

if(NOT DEFINED SOURCE_DIRECTORY)
	message(FATAL_ERROR "SOURCE_DIRECTORY is required")
endif()

set(allowlist_file "${SOURCE_DIRECTORY}/cmake/PublicHeaderStaticAssertAllowlist.txt")
file(STRINGS "${allowlist_file}" allowlist_entries)
list(FILTER allowlist_entries EXCLUDE REGEX "^[ \\t]*(#|$)")
list(LENGTH allowlist_entries allowlist_count)
if(allowlist_count EQUAL 0)
	message(FATAL_ERROR "The public-header static_assert allowlist is empty")
endif()

math(EXPR allowlist_last "${allowlist_count} - 1")
foreach(index RANGE 0 ${allowlist_last})
	set(allowlist_used_${index} FALSE)
endforeach()

file(GLOB_RECURSE public_headers "${SOURCE_DIRECTORY}/include/SimdLib/*.h")
set(assertion_count 0)
foreach(header IN LISTS public_headers)
	get_filename_component(header_name "${header}" NAME)
	file(READ "${header}" header_text)
	string(REPLACE ";" "<SIMDLIB_SEMICOLON>" header_text "${header_text}")
	string(REPLACE "\r\n" "\n" header_text "${header_text}")
	string(REGEX MATCHALL "static_assert[^\n]*" assertion_contexts "${header_text}")
	foreach(context IN LISTS assertion_contexts)
		string(REPLACE "<SIMDLIB_SEMICOLON>" ";" context "${context}")
		math(EXPR assertion_count "${assertion_count} + 1")
		set(matched FALSE)
		foreach(allowlist_index RANGE 0 ${allowlist_last})
			list(GET allowlist_entries ${allowlist_index} entry)
			string(REPLACE "|" ";" fields "${entry}")
			list(LENGTH fields field_count)
			if(NOT field_count EQUAL 3)
				message(FATAL_ERROR "Malformed static_assert allowlist entry: ${entry}")
			endif()
			list(GET fields 0 allowed_header)
			list(GET fields 1 allowed_substring)
			if(header_name STREQUAL allowed_header)
				string(FIND "${context}" "${allowed_substring}" match_position)
				if(NOT match_position EQUAL -1)
					set(matched TRUE)
					set(allowlist_used_${allowlist_index} TRUE)
					break()
				endif()
			endif()
		endforeach()
		if(NOT matched)
			message(FATAL_ERROR "Unallowlisted static_assert in ${header}: ${context}")
		endif()
	endforeach()
endforeach()
foreach(index RANGE 0 ${allowlist_last})
	if(NOT allowlist_used_${index})
		list(GET allowlist_entries ${index} unused_entry)
		message(FATAL_ERROR "Stale static_assert allowlist entry: ${unused_entry}")
	endif()
endforeach()

message(STATUS "Validated ${assertion_count} production-header static_assert occurrences against ${allowlist_count} justified allowlist entries")