foreach(required_variable IN ITEMS TRACE_FILES OUTPUT_FILE)
    if(NOT DEFINED ${required_variable})
        message(FATAL_ERROR "${required_variable} is required")
    endif()
endforeach()

if(NOT TRACE_FILES)
    message(FATAL_ERROR "No LCOV trace files were supplied")
endif()

set(source_keys "")
foreach(trace_file IN LISTS TRACE_FILES)
    if(NOT EXISTS "${trace_file}")
        message(FATAL_ERROR "LCOV trace file does not exist: ${trace_file}")
    endif()
    file(STRINGS "${trace_file}" trace_lines ENCODING UTF-8)
    set(current_source_key "")
    foreach(trace_line IN LISTS trace_lines)
        if(trace_line MATCHES "^SF:(.*)$")
            set(source_path "${CMAKE_MATCH_1}")
            string(REPLACE "\\" "/" source_path "${source_path}")
            cmake_path(NORMAL_PATH source_path)
            string(SHA256 current_source_key "${source_path}")
            if(NOT DEFINED source_path_${current_source_key})
                set(source_path_${current_source_key} "${source_path}")
                list(APPEND source_keys "${current_source_key}")
            endif()
        elseif(current_source_key AND trace_line MATCHES "^FN:([0-9]+),(.*)$")
            set(function_line "${CMAKE_MATCH_1}")
            set(function_name "${CMAKE_MATCH_2}")
            string(SHA256 function_key
                "${current_source_key}|${function_line}|${function_name}")
            if(NOT DEFINED function_name_${function_key})
                set(function_name_${function_key} "${function_name}")
                set(function_line_${function_key} "${function_line}")
                set(function_count_${function_key} 0)
                list(APPEND function_keys_${current_source_key} "${function_key}")
            endif()
            string(SHA256 function_name_key "${function_name}")
            set(record_function_${record_serial}_${function_name_key} "${function_key}")
        elseif(current_source_key AND trace_line MATCHES "^FNDA:([0-9]+),(.*)$")
            set(function_execution_count "${CMAKE_MATCH_1}")
            set(function_name "${CMAKE_MATCH_2}")
            string(SHA256 function_name_key "${function_name}")
            set(function_key
                "${record_function_${record_serial}_${function_name_key}}")
            if(NOT function_key)
                message(FATAL_ERROR
                    "FNDA record has no matching FN record in ${trace_file}: ${trace_line}")
            endif()
            math(EXPR function_count_${function_key}
                "${function_count_${function_key}} + ${function_execution_count}")
        elseif(current_source_key AND trace_line MATCHES "^BRDA:([0-9]+),([^,]+),([^,]+),([^,]+)$")
            set(branch_line "${CMAKE_MATCH_1}")
            set(branch_block "${CMAKE_MATCH_2}")
            set(branch_number "${CMAKE_MATCH_3}")
            set(branch_taken "${CMAKE_MATCH_4}")
            string(SHA256 branch_key
                "${current_source_key}|${branch_line}|${branch_block}|${branch_number}")
            if(NOT DEFINED branch_taken_${branch_key})
                set(branch_line_${branch_key} "${branch_line}")
                set(branch_block_${branch_key} "${branch_block}")
                set(branch_number_${branch_key} "${branch_number}")
                set(branch_taken_${branch_key} "${branch_taken}")
                list(APPEND branch_keys_${current_source_key} "${branch_key}")
            elseif(NOT "${branch_taken}" STREQUAL "-")
                if("${branch_taken_${branch_key}}" STREQUAL "-")
                    set(branch_taken_${branch_key} 0)
                endif()
                math(EXPR branch_taken_${branch_key}
                    "${branch_taken_${branch_key}} + ${branch_taken}")
            endif()
        elseif(current_source_key AND trace_line MATCHES "^DA:([0-9]+),([0-9]+)(,.*)?$")
            set(line_number "${CMAKE_MATCH_1}")
            set(line_count "${CMAKE_MATCH_2}")
            if(NOT DEFINED line_count_${current_source_key}_${line_number})
                set(line_count_${current_source_key}_${line_number} 0)
                list(APPEND line_numbers_${current_source_key} "${line_number}")
            endif()
            math(EXPR line_count_${current_source_key}_${line_number}
                "${line_count_${current_source_key}_${line_number}} + ${line_count}")
        endif()
    endforeach()
endforeach()

if(NOT source_keys)
    message(FATAL_ERROR "The LCOV traces contain no source records")
endif()

list(REMOVE_DUPLICATES source_keys)
list(SORT source_keys)
file(WRITE "${OUTPUT_FILE}" "")
foreach(source_key IN LISTS source_keys)
    file(APPEND "${OUTPUT_FILE}" "TN:\nSF:${source_path_${source_key}}\n")

    set(source_function_keys "${function_keys_${source_key}}")
    list(REMOVE_DUPLICATES source_function_keys)
    list(SORT source_function_keys)
    foreach(function_key IN LISTS source_function_keys)
        file(APPEND "${OUTPUT_FILE}"
            "FN:${function_line_${function_key}},${function_name_${function_key}}\n")
    endforeach()
    set(functions_hit 0)
    foreach(function_key IN LISTS source_function_keys)
        set(function_count "${function_count_${function_key}}")
        file(APPEND "${OUTPUT_FILE}"
            "FNDA:${function_count},${function_name_${function_key}}\n")
        if(function_count GREATER 0)
            math(EXPR functions_hit "${functions_hit} + 1")
        endif()
    endforeach()
    list(LENGTH source_function_keys functions_found)
    file(APPEND "${OUTPUT_FILE}" "FNF:${functions_found}\nFNH:${functions_hit}\n")

    set(source_branch_keys "${branch_keys_${source_key}}")
    list(SORT source_branch_keys)
    set(branches_hit 0)
    foreach(branch_key IN LISTS source_branch_keys)
        set(branch_taken "${branch_taken_${branch_key}}")
        file(APPEND "${OUTPUT_FILE}"
            "BRDA:${branch_line_${branch_key}},${branch_block_${branch_key}},${branch_number_${branch_key}},${branch_taken}\n")
        if(NOT branch_taken STREQUAL "-" AND branch_taken GREATER 0)
            math(EXPR branches_hit "${branches_hit} + 1")
        endif()
    endforeach()
    list(LENGTH source_branch_keys branches_found)
    file(APPEND "${OUTPUT_FILE}" "BRF:${branches_found}\nBRH:${branches_hit}\n")

    set(source_line_numbers "${line_numbers_${source_key}}")
    list(REMOVE_DUPLICATES source_line_numbers)
    list(SORT source_line_numbers COMPARE NATURAL)
    set(lines_hit 0)
    foreach(line_number IN LISTS source_line_numbers)
        set(line_count "${line_count_${source_key}_${line_number}}")
        file(APPEND "${OUTPUT_FILE}" "DA:${line_number},${line_count}\n")
        if(line_count GREATER 0)
            math(EXPR lines_hit "${lines_hit} + 1")
        endif()
    endforeach()
    list(LENGTH source_line_numbers lines_found)
    file(APPEND "${OUTPUT_FILE}"
        "LF:${lines_found}\nLH:${lines_hit}\nend_of_record\n")
endforeach()
