cmake_minimum_required(VERSION 3.31)

foreach(required_variable IN ITEMS MODE TEST_DIRECTORY INVENTORY_FILE)
	if(NOT DEFINED ${required_variable} OR "${${required_variable}}" STREQUAL "")
		message(FATAL_ERROR "RecordTestInventory requires ${required_variable}")
	endif()
endforeach()
if(NOT MODE MATCHES "^(RECORD|VALIDATE)$")
	message(FATAL_ERROR "RecordTestInventory MODE must be RECORD or VALIDATE")
endif()

# @brief Produces a deterministic inventory of executables owned by one CTest tree.
# @param output_variable Variable that receives newline-delimited path and SHA-256 pairs.
function(simdlib_collect_test_inventory output_variable)
	set(ctest_arguments --test-dir "${TEST_DIRECTORY}" -N -V)
	if(DEFINED CONFIGURATION AND NOT "${CONFIGURATION}" STREQUAL "")
		list(APPEND ctest_arguments -C "${CONFIGURATION}")
	endif()
	execute_process(
		COMMAND "${CMAKE_CTEST_COMMAND}" ${ctest_arguments}
		RESULT_VARIABLE ctest_result
		OUTPUT_VARIABLE ctest_output
		ERROR_VARIABLE ctest_error)
	if(NOT ctest_result EQUAL 0)
		message(FATAL_ERROR "Unable to enumerate tests in ${TEST_DIRECTORY}: ${ctest_error}")
	endif()

	set(executables "")
	string(REPLACE "\r\n" "\n" ctest_output "${ctest_output}")
	string(REGEX MATCHALL "Test command: [^\n\r]+" command_lines "${ctest_output}")
	foreach(command_line IN LISTS command_lines)
		if(NOT command_line MATCHES "^Test command: \"?([^\" ]+)")
			continue()
		endif()
		set(executable "${CMAKE_MATCH_1}")
		cmake_path(ABSOLUTE_PATH executable NORMALIZE OUTPUT_VARIABLE absolute_executable)
		cmake_path(IS_PREFIX TEST_DIRECTORY "${absolute_executable}" NORMALIZE executable_is_owned)
		if(NOT executable_is_owned OR NOT EXISTS "${absolute_executable}" OR IS_DIRECTORY "${absolute_executable}")
			continue()
		endif()
		list(APPEND executables "${absolute_executable}")
	endforeach()
	list(REMOVE_DUPLICATES executables)
	list(SORT executables)

	set(entries "")
	foreach(executable IN LISTS executables)
		file(SHA256 "${executable}" executable_hash)
		list(APPEND entries "${executable}|${executable_hash}")
	endforeach()
	string(REPLACE ";" "\n" artifact_inventory "${entries}")
	set(inventory "schema=simdlib.test-artifact-inventory.v1\n")
	if(NOT artifact_inventory STREQUAL "")
		string(APPEND inventory "${artifact_inventory}\n")
	endif()
	set(${output_variable} "${inventory}" PARENT_SCOPE)
endfunction()

if(MODE STREQUAL "RECORD")
	simdlib_collect_test_inventory(current_inventory)
	cmake_path(GET INVENTORY_FILE PARENT_PATH inventory_directory)
	file(MAKE_DIRECTORY "${inventory_directory}")
	set(temporary_file "${INVENTORY_FILE}.tmp")
	file(WRITE "${temporary_file}" "${current_inventory}")
	file(RENAME "${temporary_file}" "${INVENTORY_FILE}")
elseif(NOT EXISTS "${INVENTORY_FILE}")
	message(FATAL_ERROR "Required test artifact inventory is missing: ${INVENTORY_FILE}")
else()
	file(STRINGS "${INVENTORY_FILE}" inventory_lines)
	list(POP_FRONT inventory_lines schema_line)
	if(NOT schema_line STREQUAL "schema=simdlib.test-artifact-inventory.v1")
		message(FATAL_ERROR "Test artifact inventory has an unsupported schema: ${INVENTORY_FILE}")
	endif()
	foreach(inventory_line IN LISTS inventory_lines)
		if(NOT inventory_line MATCHES "^(.+)\\|([0-9a-fA-F]+)$")
			message(FATAL_ERROR "Test artifact inventory entry is malformed: ${inventory_line}")
		endif()
		set(executable "${CMAKE_MATCH_1}")
		set(recorded_hash "${CMAKE_MATCH_2}")
		if(NOT EXISTS "${executable}" OR IS_DIRECTORY "${executable}")
			message(FATAL_ERROR "Required test artifact is missing: ${executable}")
		endif()
		file(SHA256 "${executable}" current_hash)
		if(NOT current_hash STREQUAL recorded_hash)
			message(FATAL_ERROR "Required test artifact is stale: ${executable}")
		endif()
	endforeach()
endif()
