cmake_minimum_required(VERSION 3.31)

foreach(required_variable IN ITEMS MODE RECORD_FILE)
	if(NOT DEFINED ${required_variable} OR "${${required_variable}}" STREQUAL "")
		message(FATAL_ERROR "RecordArtifactHashes requires ${required_variable}")
	endif()
endforeach()
if(NOT MODE MATCHES "^(RECORD|VALIDATE)$")
	message(FATAL_ERROR "RecordArtifactHashes MODE must be RECORD or VALIDATE")
endif()

# @brief Hashes a sorted set of required build artifacts.
# @param artifact_paths Paths to hash.
# @param output_variable Variable that receives the machine-readable record body.
function(simdlib_hash_artifacts artifact_paths output_variable)
	set(paths "${artifact_paths}")
	list(REMOVE_DUPLICATES paths)
	list(SORT paths)
	set(record "schema=simdlib.artifact-record.v1\n")
	foreach(artifact_path IN LISTS paths)
		if(NOT EXISTS "${artifact_path}" OR IS_DIRECTORY "${artifact_path}")
			message(FATAL_ERROR "Required build artifact is missing: ${artifact_path}")
		endif()
		file(SHA256 "${artifact_path}" artifact_hash)
		string(APPEND record "${artifact_path}|${artifact_hash}\n")
	endforeach()
	set(${output_variable} "${record}" PARENT_SCOPE)
endfunction()

if(MODE STREQUAL "RECORD")
	if(NOT DEFINED ARTIFACTS OR "${ARTIFACTS}" STREQUAL "")
		message(FATAL_ERROR "RecordArtifactHashes RECORD mode requires ARTIFACTS")
	endif()
	string(REPLACE "|" ";" artifact_paths "${ARTIFACTS}")
	simdlib_hash_artifacts("${artifact_paths}" current_record)
	cmake_path(GET RECORD_FILE PARENT_PATH record_directory)
	file(MAKE_DIRECTORY "${record_directory}")
	file(WRITE "${RECORD_FILE}.tmp" "${current_record}")
	file(RENAME "${RECORD_FILE}.tmp" "${RECORD_FILE}")
elseif(NOT EXISTS "${RECORD_FILE}")
	message(FATAL_ERROR "Required build artifact record is missing: ${RECORD_FILE}")
else()
	file(STRINGS "${RECORD_FILE}" recorded_lines)
	list(POP_FRONT recorded_lines schema_line)
	if(NOT schema_line STREQUAL "schema=simdlib.artifact-record.v1")
		message(FATAL_ERROR "Build artifact record has an unsupported schema: ${RECORD_FILE}")
	endif()
	set(artifact_paths "")
	foreach(recorded_line IN LISTS recorded_lines)
		string(REGEX REPLACE "\\|[0-9a-fA-F]+$" "" artifact_path "${recorded_line}")
		list(APPEND artifact_paths "${artifact_path}")
	endforeach()
	simdlib_hash_artifacts("${artifact_paths}" current_record)
	file(READ "${RECORD_FILE}" recorded_record)
	if(NOT current_record STREQUAL recorded_record)
		message(FATAL_ERROR "Build artifact record is stale: ${RECORD_FILE}")
	endif()
endif()
