cmake_minimum_required(VERSION 4.4)

if(NOT DEFINED RECORD_INDEX OR "${RECORD_INDEX}" STREQUAL "")
	message(FATAL_ERROR "ValidateCodegenRecords requires RECORD_INDEX")
endif()
if(NOT EXISTS "${RECORD_INDEX}")
	message(FATAL_ERROR "Required generated-code record index is missing: ${RECORD_INDEX}")
endif()

# @brief Validates one generated-code record and its hashed inputs.
# @param record_file Machine-readable comparison or diagnostic record.
function(simdlib_validate_codegen_record record_file)
	if(NOT EXISTS "${record_file}")
		message(FATAL_ERROR "Required generated-code record is missing: ${record_file}")
	endif()
	file(READ "${record_file}" record_json)
	string(JSON schema ERROR_VARIABLE schema_error GET "${record_json}" schema)
	if(schema_error OR NOT schema STREQUAL "simdlib.codegen-record.v1")
		message(FATAL_ERROR "Generated-code record has an unsupported schema: ${record_file}")
	endif()
	string(JSON result ERROR_VARIABLE result_error GET "${record_json}" result)
	if(result_error OR NOT result MATCHES "^(exact-parity|accepted-compiler-exception|recorded-difference|recorded-diagnostic)$")
		message(FATAL_ERROR "Generated-code record has an invalid result: ${record_file}")
	endif()

	foreach(input_name IN ITEMS wrapper raw)
		string(JSON input_path ERROR_VARIABLE path_error GET "${record_json}" inputs ${input_name} path)
		string(JSON input_hash ERROR_VARIABLE hash_error GET "${record_json}" inputs ${input_name} sha256)
		if(path_error OR hash_error OR NOT EXISTS "${input_path}")
			message(FATAL_ERROR "Generated-code record input is missing: ${record_file} (${input_name})")
		endif()
		file(SHA256 "${input_path}" current_hash)
		if(NOT current_hash STREQUAL input_hash)
			message(FATAL_ERROR "Generated-code record input is stale: ${record_file} (${input_name})")
		endif()
	endforeach()

	string(JSON tool_path ERROR_VARIABLE tool_path_error GET "${record_json}" tool path)
	string(JSON tool_hash ERROR_VARIABLE tool_hash_error GET "${record_json}" tool sha256)
	if(tool_path_error OR tool_hash_error OR NOT EXISTS "${tool_path}")
		message(FATAL_ERROR "Generated-code record tool is missing: ${record_file}")
	endif()
	file(SHA256 "${tool_path}" current_tool_hash)
	if(NOT current_tool_hash STREQUAL tool_hash)
		message(FATAL_ERROR "Generated-code record tool identity is stale: ${record_file}")
	endif()
endfunction()

file(STRINGS "${RECORD_INDEX}" record_files)
foreach(record_file IN LISTS record_files)
	if(NOT record_file STREQUAL "")
		simdlib_validate_codegen_record("${record_file}")
	endif()
endforeach()
